CREATE TABLE PRODUCTOS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(150),
	PRECIO DECIMAL(5,2) NOT NULL,
	STOCK INT NOT NULL,
	CATEGORIA_ID INT,
	FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID)
);

CREATE TABLE USUARIOS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	CONTRA VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100),
	DIRECCION VARCHAR(100),
	TELEFONO VARCHAR(20),
	ROL VARCHAR(25) NOT NULL
);
