CREATE TABLE CATEGORIAS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PRODUCTOS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(150),
	PRECIO DECIMAL(5,2) NOT NULL,
	STOCK INT NOT NULL,
	CATEGORIA_ID INT,
	FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID)
);

CREATE TABLE USUARIOS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	CONTRA VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100),
	DIRECCION VARCHAR(100),
	TELEFONO VARCHAR(20),
	ROL VARCHAR(25) NOT NULL
);

CREATE TABLE PEDIDOS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USUARIO_ID INT NOT NULL,
	TOTAL DECIMAL(10,2) NOT NULL,
	ESTADO ENUM('Pendiente', 'Pagado', 'Enviado', 'Entregado', 'Cancelado') DEFAULT 'Pendiente',
	FECHA_PEDIDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
);

CREATE TABLE DETALLES_PEDIDO (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	PEDIDO_ID INT NOT NULL,
	PRODUCTO_ID INT NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO DECIMAL(5,2) NOT NULL,
	FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS(ID),
	FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID)
);